--=================== таблица Пользователи
 CREATE TABLE IF NOT EXISTS users (
              id 		INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              email 	VARCHAR(100) NOT NULL,
              login 	VARCHAR(100) NOT NULL,
              name		VARCHAR(100),
              birthday 	DATE
          );
COMMENT ON TABLE users IS 'Таблица хранит данные о пользователях';
COMMENT ON COLUMN users.id IS 'Уникальный идентификатор пользователя, первичный ключ';
COMMENT ON COLUMN users.email IS 'Электронная почта';
COMMENT ON COLUMN users.login IS 'Логин пользователя';
COMMENT ON COLUMN users.name IS 'Имя для отображения';
COMMENT ON COLUMN users.birthday IS 'Дата рождения';
 
--=================== таблица Друзья
CREATE TABLE IF NOT EXISTS friends (
              user_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
              friend_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
              CONSTRAINT friends_pk PRIMARY KEY (user_id,friend_id)
          );
COMMENT ON TABLE friends IS 'Таблица хранит данные о друзьях пользователя.';
COMMENT ON COLUMN friends.user_id IS 'Идентификатор пользователя';
COMMENT ON COLUMN friends.friend_id IS 'Идентификатор друга пользователя';

--=================== таблица возрастных ограничений для фильма, Рейтинг MPA 
 CREATE TABLE IF NOT EXISTS mpa_ratings (
              rating_id 		INTEGER PRIMARY KEY,
              rating_code   	VARCHAR(10) NOT NULL,
              description   	VARCHAR(100)
          );	
COMMENT ON TABLE mpa_ratings IS 'Хранит возможные возрастные ограничения для фильма, рейтинг ассоциации кинокомпаний (Motion Picture Association, сокращённо МРА)';
COMMENT ON COLUMN mpa_ratings.rating_id IS 'Уникальный идентификатор рейтинга, первичный ключ';
COMMENT ON COLUMN mpa_ratings.rating_code IS 'Код рейтинга';
COMMENT ON COLUMN mpa_ratings.description IS 'Описание рейтинга';

--=================== таблица Фильмы
 CREATE TABLE IF NOT EXISTS films (
              id 				INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              name 	    		VARCHAR(100) NOT NULL,
              description 		VARCHAR(200),
              release_date 		DATE,
              duration			INTEGER,
              rating_id			INTEGER REFERENCES mpa_ratings (rating_id) ON DELETE RESTRICT
          );
COMMENT ON TABLE films IS 'Таблица хранит данные о фильмах';
COMMENT ON COLUMN films.id IS 'Уникальный идентификатор фильма, первичный ключ';
COMMENT ON COLUMN films.name IS 'Название фильма';
COMMENT ON COLUMN films.description IS 'Описание фильма';
COMMENT ON COLUMN films.release_date IS 'Дата выхода фильма';
COMMENT ON COLUMN films.duration IS 'Продолжительность';
COMMENT ON COLUMN films.rating_id IS 'Идентификатор рейтинга фильма от ассоциации MPA';

--=================== таблица Лайков
CREATE TABLE IF NOT EXISTS likes (
              film_id INTEGER REFERENCES films (id) ON DELETE CASCADE,
              user_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
              CONSTRAINT likes_pk PRIMARY KEY (film_id,user_id)
          );
COMMENT ON TABLE likes IS 'Таблица хранит данные о лайков от пользователей поставленных фильму';
COMMENT ON COLUMN likes.film_id IS 'Идентификатор фильма';
COMMENT ON COLUMN likes.user_id IS 'Идентификатор пользователя';

--=================== таблица Жарны
 CREATE TABLE IF NOT EXISTS genres (
              genre_id 		INTEGER PRIMARY KEY,
              genre_name   	VARCHAR(100) NOT NULL
          );	
COMMENT ON TABLE genres IS 'Хранит возможные жанры фильмов';
COMMENT ON COLUMN genres.genre_id IS 'Уникальный идентификатор жанра, первичный ключ';
COMMENT ON COLUMN genres.genre_name IS 'Наименование жанра';

--=================== таблица жанров которым принадлежит фильм
CREATE TABLE IF NOT EXISTS film_genres (
              film_id INTEGER REFERENCES films (id) ON DELETE CASCADE,
              genre_id INTEGER REFERENCES genres (genre_id) ON DELETE RESTRICT,
              CONSTRAINT film_genres_pk PRIMARY KEY (film_id,genre_id)
          );
COMMENT ON TABLE film_genres IS 'Таблица хранит данные о жанрах которым принадлежит фильм';
COMMENT ON COLUMN film_genres.film_id IS 'Идентификатор фильма';
COMMENT ON COLUMN film_genres.genre_id IS 'Идентификатор жанра';